enum Colors {
	WHITE = "#FFFFFF",
	BLACK = "#000000",
	VIKTORIA_VIOLET = "#7132D7",
	VIKTORIA_VIOLET_DARK = "#4C10AD",
	VIKTORIA_BG_GREY = "#ECECEC",
	VIKTORIA_BLUE = "#007AFF",
	VIKTORIA_TITLE_GREY = "#484A4F",
	VIKTORIA_FORM_GREY = "#717B8C",
	VIKTORIA_SIDE_GREY = "#4C535F",
	VIKTORIA_BORDER_GREY = "#717B8C",
	VIKTORIA_BORDER_SMALL_IMG = "#717B8C",
	VIKTORIA_BORDER_PASS_INPUT = "#E0E4EC",
	VIKTORIA_BG_PASS_INPUT = "#FAFBFC",
	VIKTORIA_TXT_PASS_INPUT = "#8D98AA",
	VIKTORIA_BG_PASS_BTN = "#F73C49",
	VIKTORIA_RED = "#FF6162",
}

export default Colors;
